services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    depends_on:
      - db
    environment:
      - SESSION_SECRET=secret-key
      - DB_HOST=db
      - MYSQL_DATABASE=my_dbname
      - MYSQL_USER=my_db_username
      - MYSQL_PASSWORD=my_db_password
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=my_dbname
      - MYSQL_USER=my_db_username
      - MYSQL_PASSWORD=my_db_password
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
  test:
    build: .
    command: npm test
    depends_on:
      - app
    volumes:
      - ./node_modules:/app/node_modules
      - .:/app
volumes:
  db_data: {}
